# The Schrödinger Equation {#Schrodinger}

In 1925, Erwin Schrödinger and Werner Heisenberg independently developed the new quantum theory. Schrödinger's method involves partial differential equations, whereas Heisenberg's method employs matrices; however, a year later the two methods were shown to be mathematically equivalent. Most textbooks begin with Schrödinger's equation, since it seems to have a better physical interpretation via the classical wave equation. Indeed, the Schrödinger equation can be viewed as a form of the wave equation applied to matter waves.

## The Time-Independent Schrödinger Equation

We can start the derivation of the single-particle time-independent Schrödinger equation (TISEq) from the equation that describes the motion of a wave in classical mechanics:

\begin{equation}
\psi(x,t)=\exp[i(kx-\omega t)],
(\#eq:sch1)
\end{equation}

where $x$ is the position, $t$ is time, $k=\frac{2\pi}{\lambda}$ is the wave vector, and $\omega=2\pi\nu$ is the angular frequency of the wave. If we are not concerned with the time evolution, we can consider uniquely the derivatives of eq. \@ref(eq:sch1) with respect to the location, which are:

\begin{equation}
\begin{aligned}
\frac{\partial \psi}{\partial x} &=ik\exp[i(kx-\omega t)] = ik\psi, \\
\frac{\partial^2 \psi}{\partial x^2} &=i^2k^2\exp[i(kx-\omega t)] = -k^2\psi,
\end{aligned}
(\#eq:sch2)
\end{equation}

where we have used the fact that $i^2=-1$. 

Assuming that particles behaves as wave—as proven by de Broglie's we can now use the first of de Broglie's equation, eq. \@ref(eq:wp1b), we can replace $k=\frac{p}{\hbar}$ to obtain:

\begin{equation}
\frac{\partial^2 \psi}{\partial x^2} = -\frac{p^2\psi}{\hbar^2},
(\#eq:sch3)
\end{equation}

which can be rearranged to:

\begin{equation}
p^2 \psi = -\hbar^2 \frac{\partial^2 \psi}{\partial x^2}.
(\#eq:sch4)
\end{equation}

The total energy associated with a wave moving in space is simply the sum of its kinetic and potential energies:

\begin{equation}
E = \frac {p^{2}}{2m} + V(x),
(\#eq:sch5)
\end{equation}

from which we can obtain:

\begin{equation}
p^2 = 2m[E - V(x)],
(\#eq:sch6)
\end{equation}

which we can then replace into eq. \@ref(eq:sch4) to obtain:

\begin{equation}
2m[E-V(x)]\psi = - \hbar^2 \frac{\partial^2 \psi}{\partial x^2},
(\#eq:sch7)
\end{equation}

which can then be rearranged to the famous **time-independent Schrödinger equation (TISEq)**:

\begin{equation}
- \frac{\hbar^2}{2m} \frac{\partial^2 \psi}{\partial x^2} + V(x) \psi = E\psi,
(\#eq:TISEq)
\end{equation}

A two-body problem can also be treated by this equation if the mass $m$ is replaced with a reduced mass $\mu = \frac{m_1 m_2}{m_1+m_2}$.


## The Time-Dependent Schrödinger Equation

Unfortunately, the analogy with the classical wave equation that allowed us to obtain the TISEq in the previous section cannot be extended to the time domain by considering the equation that involves the partial first derivative with respect to time. Schrödinger himself presented his time-independent equation first, and then went back and postulated the more general time-dependent equation. We are following here the same strategy and just give the time-independent variable as a postulate. The single-particle time-dependent Schrödinger equation is:

\begin{equation}
i\hbar\frac{\partial \psi(x,t)}{\partial t}=-\frac{\hbar^2}{2m} \frac{\partial^2 \psi(x,t)}{\partial x^2}+V(x)\psi(x,t)
(\#eq:TDSEq)
\end{equation}

where $V \in \mathbb{R}^{n}$ represents the potential energy of the system.
Obviously, the time-dependent equation can be used to derive the time-independent equation. If we write the wavefunction as a product of spatial and temporal terms,  $\psi(x, t) = \psi(x) f(t)$, then equation \@ref(eq:TDSEq) becomes: 

\begin{equation}
\psi(x) i \hbar \frac{df(t)}{dt} = f(t) \left[-\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} + V(x) \right] \psi(x),
(\#eq:TDSEq2)
\end{equation}

which can be rearranged to:

\begin{equation}
\frac{i \hbar}{f(t)} \frac{df(t)}{dt} = \frac{1}{\psi(x)} \left[-\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} + V(x) \right] \psi(x).
(\#eq:TDSEq3)
\end{equation}

Since the left-hand side of eq. \@ref(eq:TDSEq3) is a function of $t$ only and the right hand side is a function of $x$ only, the two sides must equal a constant. If we tentatively designate this constant $E$ (since the right-hand side clearly must have the dimensions of energy), then we extract two ordinary differential equations, namely:

\begin{equation}
\frac{1}{f(t)} \frac{df(t)}{dt} = - \frac{i E}{\hbar}
(\#eq:TDSEq4)
\end{equation}

and:
\begin{equation}
-\frac{\hbar^2}{2m} \frac{\partial^2\psi(x)}{\partial x^2} + V(x) \psi(x) =
E \psi(x).
(\#eq:TDSEq5)
\end{equation}

The latter equation is the TISEq. The former equation is easily solved to yield 

\begin{equation}
f(t) = e^{-iEt / \hbar}
(\#eq:TDSEq6)
\end{equation}

The solutions of eq. \@ref(eq:TDSEq6), $f(t)$, are purely oscillatory, since $f(t)$ never changes in magnitude. Thus if:

\begin{equation}
\psi(x, t) = \psi(x) \exp\left(\frac{-iEt}{\hbar}\right),
(\#eq:TDSEq6b)
\end{equation}

then the total wave function  $\psi(x, t)$ differs from $\psi(x)$ only by a phase factor of constant magnitude. There are some interesting consequences of this. First of all, the quantity  $\vert \psi(x, t) \vert^2$ is time independent, as we can easily show: 

\begin{equation}
\vert \psi(x, t) \vert^2 = \psi^{*}(x, t) \psi(x, t)=
\psi^{*}(x)\exp\left(\frac{iEt}{\hbar}\right)\psi(x)\exp\left(\frac{-iEt}{\hbar}\right)= \psi^{*}(x) \psi(x).
(\#eq:TDSEq7)
\end{equation}

Wave functions of the form of eq. \@ref(eq:TDSEq6b) are called stationary states. The state  $\psi(x, t)$ is "stationary," but the particle it describes is not!
Of course eq. \@ref(eq:TDSEq6) represents only a particular solution to the time-dependent Schrödinger equation. The general solution is much more complicated, and the factorization of the temporal part is often not possible. The total wave function, however, can in general be written as a linear combination (superposition) of simpler terms, such as:^[This sections was adapted in part from Prof. C. David Sherrill's A Brief Review of Elementary Quantum Chemistry Notes available [here](http://vergil.chemistry.gatech.edu/notes/quantrev/node1.html).]

\begin{equation}
\psi({\bf r}, t) = \sum_i c_i e^{-iE_it / \hbar} \psi_i({\bf r}).
\end{equation}

## Solution for the Free Particle

We will now show how to solve the time independent portion for the simple system of a particle in motion and not subject to any force. By definition, this free particle does not feel any external force, therefore $V(x)=0$, and the TISEq is written simply:

\begin{equation}
- \frac{\hbar^2}{2m} \frac{d^2\psi}{dx^2} = E \psi(x).
(\#eq:FP1)
\end{equation}

This equation can be rearranged to:

\begin{equation}
\frac{d^2\psi}{dx^2} =- \frac{2mE}{\hbar^2} \psi(x),
(\#eq:FP2)
\end{equation}

which corresponds to a mathematical problem where the second derivative of a function should be equal to a constant, $- \frac{2mE}{\hbar^2}$ multiplied by the function itself. Such a problem is easily solved by the function:

\begin{equation}
\psi(x) = A \exp(\pm ikx).
(\#eq:FP3)
\end{equation}

The first and second derivatives of this function are:

\begin{equation}
\begin{aligned}
\frac{d \psi(x)}{dx} &= \pm ik A \exp(\pm ikx) = \pm ik \psi(x) \\
\frac{d^2 \psi(x)}{dx^2} &= \mp k^2  A \exp(\pm ikx) = -(\pm k^2) \psi(x). 
\end{aligned}
(\#eq:FP4)
\end{equation}

Comparing the second derivative in eq. \@ref(eq:FP4) with eq. \@ref(eq:FP2), we immediately see that if we set:

\begin{equation}
k^2 = \frac{2mE}{\hbar^2},
(\#eq:FP5)
\end{equation}

we solve the original differential equation. Considering de Broglie's equation, eq. \@ref(eq:wp1b), we can replace $k=\frac{p}{\hbar}$, to obtain:

\begin{equation}
E = \frac{k^2 \hbar^2}{2m} = \frac{p^2}{2m},
(\#eq:FP6)
\end{equation}

which is exactly the classical value of the kinetic energy of a free particle moving in one direction of space. Since the function in eq. \@ref(eq:FP3) solves the Schrödinger equation for the free particle, it is called an *eigenfunction* (or *eigenstate*) of the TISEq. The energy result of eq. \@ref(eq:FP6) is called *eigenvalue* of the TISEq. Notice that, since $k$ is continuous in the eigenfunction, the energy eigenvalue is also continuous (i.e., all values of $E$ are acceptable).

## Chapter Review {#rev3}
### Study Questions {#quest3}

**1. The starting point for deriving the 1D time-independent Schrödinger equation in Chapter 3 is a classical wave of which form?**

a. $\psi(x,t) = \exp[-kx + \omega t]$
b. $\psi(x,t) = \cos(kx - \omega t)$  
c. $\psi(x,t) = \sin(kx + \omega t)$  
d. $\psi(x,t) = \exp[i(kx - \omega t)]$
e. $\psi(x,t) = kx + \omega t$

---

**2. For a two-body problem, the single-particle time independent Schrödinger equation can be used if the mass $m$ is replaced by what?**

a. The total mass $m_1 + m_2$
b. The reduced mass $\mu = \dfrac{m_1 m_2}{m_1 + m_2}$
c. The mass difference $|m_1 - m_2|$
d. The geometric mean $\sqrt{m_1 m_2}$
e. Twice the lighter mass  

---

**3. Which of the following equation is the correct time-dependent Schrödinger equation for one particle?**

a. $i\hbar \dfrac{\partial \psi(x,t)}{\partial t} = -\dfrac{\hbar^2}{2m}\dfrac{\partial^2 \psi(x,t)}{\partial x^2} + V(x)\psi(x,t)$  
b. $\hbar \dfrac{\partial \psi(x,t)}{\partial t} = -\dfrac{\hbar^2}{2m}\dfrac{\partial^2 \psi(x,t)}{\partial x^2} + V(x)\psi(x,t)$  
c. $i \dfrac{\partial^2 \psi(x,t)}{\partial t^2} = -\dfrac{\hbar^2}{2m}\dfrac{\partial^2 \psi(x,t)}{\partial x^2}$  
d. $i\hbar \dfrac{\partial^2 \psi(x,t)}{\partial t^2} = V(x)\psi(x,t)$  
e. $\dfrac{\partial \psi(x,t)}{\partial t} = -\dfrac{\hbar}{2m}\dfrac{\partial^2 \psi(x,t)}{\partial x^2}$  


---

**4. For which of the following wave functions we can separate the variables in the Schrödinger equation?**

a. $\psi(x,t) = \psi(x) + f(t)$  
b. $\psi(x,t) = \psi(x) f(t)$  
c. $\psi(x,t) = \psi(x)^2/f(t)$  
d. $\psi(x,t) = x f(t)$  
e. $\psi(x,t) = \psi(x) f(t)^2$  

---

**5. After separation of variables, the time-dependent Schrödinger equation yields two ordinary differential equations with a common constant. Which one?**

a. The mass $m$  
b. The momentum $p$  
c. The angular frequency $\omega$  
d. The energy $E$  
e. The wave number $k$  

---

**6. What is the time dependence of the probability density $|\psi(x,t)|^2$ of a stationary state?**

a. It increases linearly with time  
b. It decreases exponentially with time  
c. It oscillates sinusoidally with time  
d. It is time independent  
e. It diverges for large times  

---

**7. For the free particle in 1D, which of the following properties does the potential $V(x)$ have?**

a. It is a constant nonzero value 
b. It is infinite at the origin  
c. It is zero everywhere  
d. It is linear in $x$  
d. It is harmonic in $x^2$  

---

**8. Which of the following is a suitable solution for the free-particle time independent Schrödinger equation?**

a. $\psi(x) = A e^{\pm i k x}$  
b. $\psi(x) = A x$  
c. $\psi(x) = A e^{k x}$  
d. $\psi(x) = A \cosh(kx)$  
e. $\psi(x) = A \delta(x)$  

---

**9. What is the energy eigenvalue for the free particle?**

a. $E = p^2$  
b. $E = \dfrac{1}{2} m p^2$  
c. $E = \hbar p$  
d. $E = \dfrac{\hbar^2}{2m p^2}$  
e. $E = \dfrac{p^2}{2m}$  

---

**10. What is a key difference between the free particle and bound systems regarding energy eigenvalues?**

a. Free-particle energies are always zero  
b. Free-particle energies are always negative  
c. Free-particle energies are always degenerate  
d. Free-particle energies form a continuous spectrum, while bound systems have discrete levels
e. Free-particle energies do not depend on mass  

---

`r if (knitr::is_html_output()) {
  '
  Answers: <span style="cursor: pointer; color: blue; text-decoration: underline;" onclick="document.getElementById(\'reveal-inline-content\').style.display=\'inline\'; this.style.display=\'none\';">
    Click to reveal
  </span>
  <span id="reveal-inline-content" style="display: none;">
            1.d, 2.b, 3.a, 4.b, 5.d, 6.d, 7.c, 8.a, 9.e, 10.d
  </span>
  '
} else if (knitr::is_latex_output()) {
  'Answers: 1.d, 2.b, 3.a, 4.b, 5.d, 6.d, 7.c, 8.a, 9.e, 10.d'
}`


