# Analytically Solvable Models {#Models}

The TISEq can be solved analytically only in a few special cases. We saw one of those special cases, the free particle, at the end of the previous chapter. In this section, we will analyze three others. Luckily, we can use these solutions to explain most of the effects in chemistry since we can combine them to describe the hydrogen atom upon which we can build more complex chemical systems, as we will show in the next chapters.

## The Particle in a Box

We can start by considering a particle constrained to move in a single dimension, under the influence of a potential $V(x)$ which is zero for  $0 \leq x \leq a$ and infinite elsewhere. Since the wavefunction is not allowed to become infinite, it must have a value of zero where $V(x)$ is infinite, so $\psi(x)$ is nonzero only within $[0,a]$. The Schrödinger equation is thus:

\begin{equation}
- \frac{\hbar^2}{2m} \frac{d^2\psi}{dx^2} = E \psi(x)
\qquad 0 \leq x \leq a.
(\#eq:PIB1)
\end{equation}

In other words, inside the box $\psi(x)$ describes a free particle, but outside the box $\psi(x)=0$. Since the Schrödinger equation involves derivatives, the function that solves it, $\psi(x)$, must be everywhere continuous and everywhere continuously differentiable. This fact means that the value of the wave function at the two extremes must be equal to zero:

\begin{equation}
\psi(0)=\psi(a)=0.
(\#eq:PIB2)
\end{equation}

Inside the box the most general solution will be of the kind:

\begin{equation}
\psi(x)=A \sin kx + B \cos kx,
(\#eq:PIB3)
\end{equation}

where $A$ and $B$ are constants that we need to determine using the two constraints in eq. \@ref(eq:PIB2). For $B$ it is straightforward to see that:

\begin{equation}
\psi(0)= 0 + B =0 \; \implies \; B=0.
(\#eq:PIB4)
\end{equation}

For $A$ we have:

\begin{equation}
\psi(a)= A\sin ka = 0,
(\#eq:PIB5)
\end{equation}

which is trivially solved by $A=0$, or by the more interesting condition of $ka=n\pi$. The trivial solution corresponds to a wave function uniformly equal to zero everywhere. This wave function is uninteresting, since it describes no particles in no boxes. The second set of solutions, however, is very interesting, since we can write it as:

\begin{equation}
\psi_n(x)= A\sin\left(\frac{n\pi x}{a} \right)\quad n=1,2,\ldots,\infty,
(\#eq:PIB6)
\end{equation}

which represents an infinite set of functions, $\psi_n(x)$, determined by a positive integer number $n$, called *quantum number*. Since these functions solve the TISEq, they are also called *eigenfunctions*, but they are not a continuous set, unlike in the previous case. To calculate the energy eigenvalues, we can replace \@ref(eq:PIB6) into eq. \@ref(eq:PIB1), to obtain:

\begin{equation}
E_n = \frac{h^2 n^2}{8 m a^2} \quad n=1,2,\ldots,\infty.
(\#eq:PIB7)
\end{equation}

A few interesting considerations can be made from the results of eq. \@ref(eq:PIB7). First, although there is an infinite number of acceptable values of the energy (eigenvalues), these values are not continuous. Second, the lowest value of the energy is not zero, and it depends on the size of the box, $a$, since:

\begin{equation}
E_1 = \frac{h^2 }{8 m a^2} \neq 0.
(\#eq:PIB8)
\end{equation}

This value is called *zero-point energy (ZPE)*, and is a purely quantum mechanical effect. Notice that we did not solve for the constant $A$. This task is not straightforward, and it can be achieved by requiring the wave function to describe one particle exclusively (we will come back to this task after chapter 7). Extending the problem to three dimensions is relatively straightforward, resulting in a set of three separate quantum numbers (one for each of the 3-dimensional coordinate $n_x,n_y,n_z$).

## The Harmonic Oscillator

We now consider a particle subject to a restoring force $F = -kx$, as might arise for a mass-spring system obeying Hooke's Law. The potential is then:

\begin{equation}
V(x) = - \int_{-\infty}^{\infty} (-kx) dx = V_0 + \frac{1}{2} kx^2.
(\#eq:HO1)
\end{equation}

If we choose the energy scale such that $V_0 = 0$ then:  $V(x) = \frac{1}{2}kx^2$, and the TISEq looks:

\begin{equation}
- \frac{\hbar^2}{2 \mu} \frac{d^2\psi}{dx^2} + \frac{1}{2} kx^2 \psi(x) =
E \psi(x)
(\#eq:HO2)
\end{equation}

After some effort, the eigenfunctions are:

\begin{equation}
\psi_n(x) = N_{n-1} H_{n-1}(\alpha^{1/2} x) e^{-\alpha x^2 / 2} \quad n=1,2,\ldots,\infty,
(\#eq:HO3)
\end{equation}

where $H_{n-1}$ is the Hermite polynomial of degree $n-1$, and $\alpha$ and $N_{n-1}$ are defined by 

\begin{equation}
\alpha = \sqrt{\frac{k \mu}{\hbar^2}} \hspace{1.5cm}
N_{n-1} = \frac{1}{\sqrt{2^{n-1} (n-1)!}} \left( \frac{\alpha}{\pi} \right)^{1/4}.
(\#eq:HO4)
\end{equation}

The eigenvalues are:

\begin{equation}
E_n = \hbar \omega \left(n - \frac{1}{2} \right),
(\#eq:HO5)
\end{equation}

with  $\omega = \sqrt{k/ \mu}$. Notice how, once again, the eigenfunctions and eigenvalues are not continuous, and the lowest energy state is not zero. In other words, the two masses of a quantum harmonic oscillator are always in motion. The frequencies at which they vibrate do not form a continuous spectrum. That is, the vibration frequency cannot take any value that we can think of, but only those given by eq. \@ref(eq:HO5). The lowest possible energy (the ZPE) will be:

\begin{equation}
E_1 = \frac{1}{2} \hbar \omega \neq 0
(\#eq:zpeH)
\end{equation}


## The Rigid Rotor

The rigid rotor is a simple model of a rotating stick in three dimensions (or, if you prefer, of a molecule). We consider the stick to consist of two point-masses at a fixed distance. We then reduce the model to a one-dimensional system by considering the rigid rotor to have one mass fixed at the origin, which is orbited by the reduced mass $\mu$, at a distance $r$. The cartesian coordinates, $x,y,z$, are then replaced by three spherical polar coordinates: the co-latitude (zenith) angle $\theta$, the longitudinal (azimuth) angle $\phi$, and the distance $r$. The TISEq of the system in spherical coordinates is:

\begin{equation}
- \frac{\hbar^2}{2I} \left[ \frac{1}{\sin \theta}
\frac{\partial}{\partial \theta} \left(\sin\theta\frac{\partial}{\partial \theta} \right) + \frac{1}{\sin^2 \theta} \frac{\partial^2}{\partial \phi^2} \right] \psi(r) = E_{\ell} \psi(r),
(\#eq:RR1)
\end{equation}

where $I=\mu r^2$ is the moment of inertia. After a little effort, the eigenfunctions can be shown to be the spherical harmonics  $Y_{\ell}^{m_{\ell}}(\theta, \phi)$.^[For a description of the spherical harmonics see [here](https://en.wikipedia.org/wiki/Spherical_harmonic)] The eigenvalues are simply: 

\begin{equation}
E_{\ell} = \frac{\hbar^2}{2I} \ell(\ell+1),
(\#eq:RR2)
\end{equation}

where $\ell=0,1,2,\ldots$ is the *azimuthal quantum number*, and $m_{\ell}=-\ell, -\ell+1, \ldots, \ell-1, \ell$ is the *magnetic quantum number*. Each energy level $E_{\ell}$ is $(2\ell+1)$-fold degenerate in $m_{\ell}$. Notice that the energy does not depend on the second index $m_{\ell}$, and the functions with fixed $m_{\ell}=-\ell,-\ell+1,\dots,\ell-1,\ell$ have the same energy. Surprisingly enough, this problem was, after all, a one-dimensional problem in disguise, similarly to the previous two cases. The two angular variables that enters the wave function are indeed completely identical to each other, with one of the two determining the energy (the magnitude of the angular momentum of the circular motion) and the other determining only an energetically irrelevant orientation for the circular motion.

Notice, however, that both these components are quantized. So, for a rigid rotor, the magnitude of the angular momentum jumps discontinuously from one value to the next,^[You can think of this as either the "speed" at which the rotor is rotating, or even better, as its "angular frequency".] and also the orientation in space at which the rotor is allowed to rotate changes discontinuously. 


## Chapter Review {#rev4}
### Study Questions {#quest4}

**1. Which three model systems are treated in this chapter as analytically solvable?**

a. Hydrogen atom, particle in a box, rigid rotor  
b. Hydrogen atom, harmonic oscillator, Morse oscillator  
c. Particle in a box, harmonic oscillator, rigid rotor  
d. Free particle, hydrogen atom, rigid rotor  
e. Particle in a box, Coulomb potential, rigid rotor  

---

**2. For the 1D infinite potential well (“particle in a box”), the potential $V(x)$ is what?**

a. Constant for all $x$  
b. Zero for $0 \le x \le a$, infinite elsewhere  
c. Linear in $x$ between 0 and $a$  
d. Harmonic in $x^2$ between 0 and $a$  
e. Zero everywhere  

---

**3. What boundary conditions are imposed on the wavefunction for the particle in a box?**

a. $\psi(0) = \psi(a) = 1$  
b. $\psi(0) = 0,\ \psi(a) = 1$  
c. $\psi(0) = \psi'(a) = 0$  
d. $\psi'(0) = \psi'(a) = 0$  
e. $\psi(0) = \psi(a) = 0$  
  
---

**4. Applying the $\psi(0)=0$ boundary condition to the particle in a box leads to which condition on the constants??**

a. $A = 0$  
b. $k = 0$  
c. $A = B$  
d. $B = 0$  
e. $A = -B$  

---

**5. Which of the following is the correct spatial dependence of the normalized eigenfunctions for the particle in a box?**

a. $\psi_n(x) \propto \sin\left(\dfrac{n\pi x}{a}\right)$  
b. $\psi_n(x) \propto \cos\left(\dfrac{n\pi x}{a}\right)$  
c. $\psi_n(x) \propto e^{ikx}$  
d. $\psi_n(x) \propto x^n$  
e. $\psi_n(x) \propto \delta(x-n)$  

---

**6. Which of the following are the energy eigenvalues $E_n$ for the particle in a box?**

a. $E_n = \dfrac{\hbar^2 n^2}{2 m a^2}$ 
b. $E_n = \dfrac{h^2 n^2}{8 m a^2}$  
c. $E_n = \dfrac{1}{2} m n^2 a^2$  
d. $E_n = \dfrac{n h c}{a}$  
e. $E_n = n \hbar \omega$  

---

**7. The harmonic oscillator eigenfunctions are expressed in terms of which special functions?**

a. Legendre polynomials $P_n$  
b. Laguerre polynomials $L_n$  
c. Hermite polynomials $H_n$  
d. Bessel functions $J_n$  
e. Spherical harmonics $Y_{\ell}^m$  

---

**8. Which of the following are the energy levels of the harmonic oscillator?**

a. $E_n = \hbar \omega \left(n + \tfrac{1}{2}\right)$  
b. $E_n = \hbar \omega n$  
c. $E_n = \dfrac{h^2 n^2}{8 m a^2}$  
d. $E_n = \dfrac{\hbar^2 n^2}{2m}$  
e. $E_n = \dfrac{1}{2} k x^2$  

---

**9. What does the rigid rotor model represent?**

a. A particle moving in a 1D infinite well  
b. Two point masses at fixed distance rotating in 3D  
c. A mass on a spring moving in 1D  
d. A free particle in 3D  
e. A charged particle in a uniform electric field  


---

**10. Which of the following are the energy levels of the rigid rotor?**

a. $E_\ell = \dfrac{\hbar^2}{2I}\,\ell(\ell+1)$  
b. $E_\ell = \hbar \omega (\ell + \tfrac{1}{2})$  
c. $E_\ell = \dfrac{h^2 \ell^2}{8 I}$  
d. $E_\ell = \dfrac{\hbar^2}{2I}\,m^2$  
e. $E_\ell = \dfrac{1}{2} I \omega^2$  

---

`r if (knitr::is_html_output()) {
  '
  Answers: <span style="cursor: pointer; color: blue; text-decoration: underline;" onclick="document.getElementById(\'reveal-inline-content\').style.display=\'inline\'; this.style.display=\'none\';">
    Click to reveal
  </span>
  <span id="reveal-inline-content" style="display: none;">
            1.c, 2.b, 3.e, 4.d, 5.a, 6.b, 7.c, 8.a, 9.b, 10.a
  </span>
  '
} else if (knitr::is_latex_output()) {
  'Answers: 1.c, 2.b, 3.e, 4.d, 5.a, 6.b, 7.c, 8.a, 9.b, 10.a'
}`


