# The Hydrogen Atom {#Hydrogen}

In this chapter we will consider the hydrogen atom as a proton fixed at the origin, orbited by an electron of reduced mass $\mu$. The potential due to electrostatic attraction is:

\begin{equation}
V(r) = - \frac{e^2}{4 \pi \varepsilon_0 r},
(\#eq:HA1)
\end{equation}

where $\varepsilon_0$ is the constant permittivity of vacuum.
The kinetic energy term in the Hamiltonian is 

\begin{equation}
K = - \frac{\hbar^2}{2 \mu} \nabla^2,
(\#eq:HA2)
\end{equation}

where $\nabla^2$ is the Laplace operator (*Laplacian*) representing the divergence of the gradient of a function. Recall that in 1-dimension the kinetic energy is proportional to the second derivative of the wave function with respect to the position. In 3-dimension, the first derivative along all three dimension of space is called gradient, which is written in cartesian coordinates $\nabla = \left(\frac{\partial}{\partial x},\frac{\partial}{\partial y},\frac{\partial}{\partial z} \right)$. The Laplacian is the divergence $\nabla \cdot$ of the gradient (effectively, it replaces the second derivatives in the 1-D case), and can be written in cartesian coordinates as $\nabla^2=\nabla\cdot\nabla=\frac{\partial^2}{\partial x^2}+\frac{\partial^2}{\partial y^2}+\frac{\partial^2}{\partial z^2}$. The TISEq for the Hydrogen atom is therefore:

\begin{equation}
{\displaystyle \left(-{\frac {\hbar ^{2}}{2\mu }}\nabla ^{2}-{\frac {e^{2}}{4\pi \varepsilon _{0}r}}\right)\psi (r,\theta ,\phi )=E\psi (r,\theta ,\phi )},
(\#eq:HA2b)
\end{equation}

which, replacing the Laplacian in spherical coordinates, becomes: 

\begin{equation}
-{\frac {\hbar ^{2}}{2\mu }}\left[{\frac {1}{r^{2}}}{\frac {\partial }{\partial r}}\left(r^{2}{\frac {\partial \psi }{\partial r}}\right)+{\frac {1}{r^{2}\sin \theta }}{\frac {\partial }{\partial \theta }}\left(\sin \theta {\frac {\partial \psi }{\partial \theta }}\right)+{\frac {1}{r^{2}\sin ^{2}\theta }}{\frac {\partial ^{2}\psi }{\partial \phi ^{2}}}\right]-{\frac {e^{2}}{4\pi \varepsilon _{0}r}}\psi =E\psi.
(\#eq:HA3)
\end{equation}

This equation seems very complicated, but comparing the term in between square brackets with the TISEq of the rigid rotor, we immediately see some connections. Eq. \@ref(eq:HA3) is a separable, partial differential equation that can be solved by factorizing the wave function $\psi(r, \theta, \phi)$ into  $R_{nl}(r)Y_{\ell}^{m_{\ell}}(\theta, \phi)$, where  $Y_{\ell}^{m_{\ell}}(\theta, \phi)$ are again the spherical harmonics that solved the TISEq for the rigid rotor. The radial part $R(r)$ obeys the equation:

\begin{equation}
- \frac{\hbar^2}{2 \mu r^2} \frac{d}{dr} \left( r^2 \frac{dR}{dr}
\right) \left[\frac{\hbar^2 \ell(\ell+1)}{2 \mu r^2} + V(r) - E \right] R(r) = 0,
(\#eq:HA4)
\end{equation}

which is called the radial equation for the hydrogen atom. The solutions of the radial part are: 

\begin{equation}
R_{n\ell}(r) = - \left[ \frac{(n - \ell - 1)!}{2n[(n+\ell)!]^3} \right]^{1/2}\left(\frac{2}{na_0}\right)^{\ell+3/2}r^{\ell} e^{-r/na_0} L_{n+\ell}^{2\ell+1}
\left( \frac{2r}{n a_0} \right)
(\#eq:HA5)
\end{equation}

where  $0 \leq \ell \leq n - 1$, and $a_0 = \frac{\varepsilon_0 h^2}{\pi \mu e^2}$ is the Bohr radius. The functions  $L_{n+\ell}^{2\ell+1}\left(\frac{2r}{na_0}\right)$ are the associated Laguerre functions. 

The hydrogen atom eigenfunctions are:

\begin{equation}
\begin{aligned}
\psi_{n\ell m_{\ell}}(r,\theta,\phi) &= R_{n\ell}(r)Y_{\ell}^{m_{\ell}}(\theta,\phi) = \\
&= - \left[ \frac{(n - \ell - 1)!}{2n[(n+\ell)!]^3} \right]^{1/2}\left(\frac{2}{na_0}\right)^{\ell+3/2}r^{\ell} e^{-r/na_0} L_{n+\ell}^{2\ell+1}
\left( \frac{2r}{n a_0} \right) Y_{\ell}^{m_{\ell}}(\theta,\phi)
\end{aligned}
(\#eq:HA6)
\end{equation}

The quantum numbers $n,\ell,m_{\ell}$ can take the following values:

$n=1,2,3,\ldots,\infty$ (principal quantum number),

$\ell =0,1,2,\ldots ,n-1$ (azimuthal quantum number),

$m_{\ell}=-\ell ,\ldots ,\ell$ (magnetic quantum number).

These functions are called the *hydrogen atom orbitals*, and are usually first encountered in introductory chemistry textbooks. Notice that—by definition—an orbital is a complex function (i.e., it has both a real and an imaginary component) that describes *exclusively* one electron. Spherical harmonics are orthogonal to each other and they can be linearly combined them to form new solution to the TISEq where the imaginary part is removed. (Because of the orthogonality of spherical harmonics, the energy spectrum will not be affected by this operation.) These corresponding real orbitals are three-dimensional function that are not easily visualized in a three-dimensional space, since they require a four-dimensional one.^[If it is not clear why you need a 4-D space to visualize a 3-D function, think at the fact that we use a 2-D space (the Cartesian plane) to visualize a 1-D function ($f(x)$).] Since there is no real consensus on what a wave function represent, the interpretation of orbitals is not straightforward.^[At least not as straightforward as it is given in introductory chemistry textbooks.] We will return on the interpretation problem in future chapters, but for now it is important to keep in mind these following facts:

- The shape of every hydrogen atom orbital—complex or real—is that of a function on the surface of a sphere (yes, this is true for every single one of them, since they all come from spherical harmonics, which are special functions defined on the surface of a sphere. Hydrogen $2p$ orbitals in real space *do not* have the shape of a dumbbell, as often is said in general chemistry textbooks. Same goes for $d, f, \ldots$ orbitals.)
- Each orbital is the mathematical description of one—and only one—electron (in other words, orbitals do not "contain" electrons, they "are" the functions that describe each electron.)
- Hydrogen orbitals are defined only for systems that contain one electron. When more than one electron is present in an atom, the TISEq in eq. \@ref(eq:HA2b) does not describe the system anymore. In these more complicated situations the TISEq cannot be solved analytically, and orbitals cannot be easily defined (we will see in chapter \@ref(Atoms) how we can circumvent this issue in an approximate manner, and why general chemistry textbook talk of orbitals for every atom and molecule.)

The hydrogen atom eigenvalues are:

\begin{equation}
E_n = - \frac{e^2}{8 \pi \varepsilon_0 a_0 n^2} \quad n=1,2,\ldots,\infty.
(\#eq:HA7)
\end{equation}

Notice how the eigenvalues (i.e., the energy spectrum) do not depend on the azimuthal and magnetic quantum numbers, $\ell$ and $m$. Energy levels with the same $n$, but different $\ell$ and/or $m$ are called *degenerate states*, since they all have the same energy. This is, once again, source of misinterpretation in most general chemistry textbook:

- According to the TISEq, the $2s$ and $2p$ orbitals of the hydrogen atom have the same energy.^[In practice, this is not true, because of a tiny effect called the [Lamb shift](https://en.wikipedia.org/wiki/Lamb_shift). The description of this effect requires to go beyond the Schrödinger equation—and essentially beyond quantum mechanics—into the field of quantum electrodynamics. The Lamb shift, however, is not what is usually depicted in general chemistry textbook as the $2s-2p$ energy difference. The difference that is usually discussed in the context of the aufbau principle is a many-electron effect, as we will discuss in chapter \@ref(Atoms), and does not apply to hydrogen.]

## Chapter Review {#rev5}
### Study Questions {#quest5}

**1. Which of the following is the electrostatic potential energy, $V(r)$, in the hydrogen atom?**

a. $V(r) = -\dfrac{e^2}{4\pi \varepsilon_0 r}$  
b. $V(r) = +\dfrac{e^2}{4\pi \varepsilon_0 r}$  
c. $V(r) = \dfrac{1}{2} k r^2$  
d. $V(r) = -G \dfrac{m_p m_e}{r}$  
e. $V(r) = 0$  

---

**2. Which of the following is the kinetic-energy operator used in the hydrogen Hamiltonian?**

a. $K = -\dfrac{\hbar^2}{2\mu}\nabla^2$  
b. $K = -\dfrac{\hbar^2}{2m_e}\dfrac{d^2}{dr^2}$  
c. $K = \dfrac{p^2}{2\mu}$  
d. $K = -\dfrac{\hbar^2}{2}\nabla$  
e. $K = -\dfrac{\hbar^2}{2M}\nabla^2$  

---

**3. How do you separate the hydrogen-atom wave function in spherical coordinates?**

a. $\psi(r,\theta,\phi) = f(r) g(\theta)$  
b. $\psi(r,\theta,\phi) = R_{n\ell}(r)\,Y_\ell^{m_\ell}(\theta,\phi)$
c. $\psi(r,\theta,\phi) = R(r) \cos\theta$  
d. $\psi(r,\theta,\phi) = Y_\ell^{m_\ell}(\theta,\phi)$  
e. $\psi(r,\theta,\phi) = R_{n\ell}(r) e^{i k r}$  

---

**4. Which special functions give the angular part of the hydrogen-atom wave functions?**

a. Hermite polynomials  
b. Associated Laguerre polynomials  
c. Bessel functions  
d. Plane waves  
e. Spherical harmonics

---

**5. How do you calculate the Bohr's radius?**

a. $a_0 = \dfrac{\varepsilon_0 h^2}{\pi \mu e^2}$  
b. $a_0 = \dfrac{4\pi \varepsilon_0 \hbar^2}{\mu e^2}$  
c. $a_0 = \dfrac{\hbar^2}{\mu e^2}$  
d. $a_0 = \dfrac{\varepsilon_0 h}{\mu e}$  
e. $a_0 = \dfrac{e^2}{4\pi \varepsilon_0 \hbar^2}$  

---

**6. Which special functions give the radial part of the hydrogen-atom wave functions?**

a. Hermite polynomials  
b. Legendre polynomials  
c. Associated Laguerre functions  
d. Spherical harmonics  
e. Bessel functions  

---

**7. What are the allowed values of the principal quantum number $n$?**

a. $n = 0, 1, 2, \dots$  
b. $n = -\infty \dots \infty$  
c. $n = 1, 2, 3, \dots$  
d. $n = \tfrac{1}{2}, \tfrac{3}{2}, \dots$  
e. $n = 2, 4, 6, \dots$  

---

**8. For a given $n$, what are the allowed values of the azimuthal quantum number $\ell$?**

a. $\ell = 0,1,2,\dots,n-1$  
b. $\ell = 1,2,\dots,n$  
c. $\ell = -n,\dots,n$  
d. $\ell = 0,\pm1,\pm2,\dots$  
e. $\ell = n$ only  

---

**9. For or a given $\ell$, what are the allowed values of the magnetic quantum number $m_\ell$?**

a. $m_\ell = 0,1,\dots,\ell$  
b. $m_\ell = 1,2,\dots,\ell$  
c. $m_\ell = -n,\dots,n$  
d. $m_\ell = \pm \tfrac{1}{2}$  
e. $m_\ell = -\ell, -\ell+1, \dots, \ell$  

---

**10. Which statement about orbitals does the chapter explicitly emphasize?**

a. Orbitals physically contain up to two electrons  
b. Each orbital is the mathematical description of one and only one electron  
c. Orbitals are purely classical trajectories  
d. Orbitals only exist for many-electron atoms  
e. Orbitals always have dumbbell shapes in real space  

---

`r if (knitr::is_html_output()) {
  '
  Answers: <span style="cursor: pointer; color: blue; text-decoration: underline;" onclick="document.getElementById(\'reveal-inline-content\').style.display=\'inline\'; this.style.display=\'none\';">
    Click to reveal
  </span>
  <span id="reveal-inline-content" style="display: none;">
            1.a, 2.a, 3.b, 4.e, 5.a, 6.c, 7.c, 8.a, 9.e, 10.b
  </span>
  '
} else if (knitr::is_latex_output()) {
  'Answers: 1.a, 2.a, 3.b, 4.e, 5.a, 6.c, 7.c, 8.a, 9.e, 10.b'
}`


