# Postulates of Quantum Mechanics {#Postulates}

In order to understand deeper quantum mechanics, scientists have derived a series of axioms that result in what are called *postulates of quantum mechanics*. These are, in fact, assumptions that we need to make to understand how the measured reality relates with the mathematics of quantum mechanics. It is important to notice that the postulates are necessary for the interpretation of the theory, but not for the mathematics behind it. Regarding of whether we interpret it or not, the mathematics is complete and consistent. In fact, as we will see in the next chapter, several controversies regarding the interpretation of the mathematics are still open, and different philosophies have been developed to rationalize the results. Recall also that there are different ways of writing the equation of quantum mechanics, all equivalent to each other (i.e., Schrödinger's differential formulation and Heisenberg's algebraic formulation that we saw in chapter \@ref(Schrodinger)). For these reasons, there is not an agreement on the number of postulates that are necessary to interpret the theory, and some philosophy and/or formulation might require more postulates than others. In this chapter, we will discuss the six postulates, as they are usually presented in chemistry and introductory physics textbooks and as they relate with a basic statistical interpretation of quantum mechanics. Regardless of the philosophical consideration on the meanings and numbers of the postulate, as well as their physical origin, these statements will make the interpretation of the theory a little easier, as we will see in the next chapter.


## Postulate 1: The Wave Function Postulate

The state of a quantum mechanical system is completely specified by a function  $\Psi({\bf r}, t)$ that depends on the coordinates of the particle(s) and on time. This function, called the wave function or state function, has the important property that  $\Psi^{*}({\bf r}, t)\Psi({\bf r}, t) d\tau$ is the probability that the particle lies in the volume element $d\tau$ located at ${\bf r}$ at time $t$.

The wave function must satisfy certain mathematical conditions because of this probabilistic interpretation. For the case of a single particle, the probability of finding it somewhere is 1, so that we have the normalization condition 

\begin{equation}
\int_{-\infty}^{\infty} \Psi^{*}({\bf r}, t) \Psi({\bf r}, t) d\tau = 1
(\#eq:post1)  
\end{equation}

It is customary to also normalize many-particle wave functions to 1. As we already saw for the particle in a box in chapter \@ref(Models), a consequence of the first postulate is that the wave function must also be single-valued, continuous, and finite, so that derivatives can be defined and calculated at each point in space. This consequence allows for operators (which typically involve derivation) to be applied without mathematical issues.

## Postulate 2: Experimental Observables

To every observable in classical mechanics there corresponds a linear, Hermitian operator in quantum mechanics. We have in part already discussed this postulate in chapter \@ref(Operators), albeit we didn't call it as such. This postulate is necessary if we require the expectation value of an operator $\hat{A}$ to be real, as it should be.

## Postulate 3: Individual Measurements

In any measurement of the observable associated with operator $\hat{A}$, the only values that will ever be observed are the eigenvalues $a$ that satisfy the eigenvalue equation:

\begin{equation}
\hat{A} \Psi = a \Psi.
(\#eq:post2)  
\end{equation}

This postulate captures the central point of quantum mechanics: the values of dynamical variables can be quantized (although it is still possible to have a continuum of eigenvalues in the case of unbound states). If the system is in an eigenstate of $\hat{A}$ with eigenvalue $a$, then any measurement of the quantity $A$ will yield $a$.
Although measurements must always yield an eigenvalue, the state does not have to be an eigenstate of $\hat{A}$ initially. 

An arbitrary state can be expanded in the complete set of eigenvectors of $\hat{A}$ $\left(\hat{A}\Psi_i = a_i \Psi_i\right)$ as:

\begin{equation}
\Psi = \sum_i^{n} c_i \Psi_i,
(\#eq:post3)  
\end{equation}

where $n$ may go to infinity. In this case, we only know that the measurement of $A$ will yield one of the values $a_i$, but we don't know which one. However, we do know the probability that eigenvalue $a_i$ will occur (it is the absolute value squared of the coefficient, $\vert c_i\vert^2$, as we obtained already in chapter \@ref(Operators)), leading to the fourth postulate below.


## Postulate 4: Expectation Values and Collapse of the Wavefunction
If a system is in a state described by a normalized wave function $\Psi$, then the average value of the observable corresponding to $\hat{A}$ is given by:

\begin{equation}
<A> = \int_{-\infty}^{\infty} \Psi^{*} \hat{A} \Psi d\tau.
(\#eq:post4)  
\end{equation}

An important consequence of the fourth postulate is that, after measurement of $\Psi$ yields some eigenvalue $a_i$, the wave function immediately "collapses" into the corresponding eigenstate $\Psi_i$. In other words, measurement affects the state of the system. This fact is used in many experimental tests of quantum mechanics, such as the Stern-Gerlach experiment. Think again at the sequential experiment that we discussed in chapter \@ref(Spin). The act of measuring the spin along one coordinate is not simply a "filtration" of some pre-existing feature of the wave function, but rather an act that changes the nature of the wave function itself, affecting the outcome of future experiments. To this act corresponds the collapse of the wave function, a process that remains unexplained to date. Notice how the controversy is not in the mathematics of the experiment, which we already discussed in the previous chapter without issues. The issues rather arise because we don't know how to define the measurement act in itself (other than the fact that it is some form of quantum mechanical procedure with clear and well-defined macroscopic outcomes). This is the reason why the collapse of the wave function is also sometimes called the *measurement problem* of quantum mechanics, and it is still a source of research and debate among modern scientists.

## Postulate 5: Time Evolution

The wave function of a system evolves in time according to the time-dependent Schrödinger equation:

\begin{equation}
\hat{H} \Psi({\bf r}, t) = i \hbar \frac{\partial \Psi}{\partial t}.
(\#eq:post5)  
\end{equation}

The central equation of quantum mechanics must be accepted as a postulate.


## Postulate 6: Pauli Exclusion Principle

If we want to describe a system with $N$ particles, we need to account not only for the position of each particle, but also for their spin. This happens because the quantity that is physically observable in quantum mechanics is not the wave function itself, but rather its square. We can start to understand why this happens by writing a multi-particle wave function using $\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right)$, with ${\bf r}_1=\{x_1,y_1,z_1,s_1\}$ being the quantum state of particle $1$ composed of its position in real space $\{x,y,z\}$ plus its spin state $s$, ${\bf r}_2=\{x_2,y_2,z_2,s_2\}$ the quantum state of particle $2$, and so on. The physically observable quantity for such a wave function will be $\left|\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right)\right|^2$. When we exchange the quantum state of two particles (let's say $1$ and $2$), this observable quantity should remain the same, since quantum particles are indistinguishable from each other:

\begin{equation}
\left|\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right)\right|^2=\left|\Psi\left({\bf r}_2,{\bf r}_1,\ldots, {\bf r}_N\right)\right|^2.
(\#eq:postpauli1)  
\end{equation}

This equality, however, can be fulfilled in two different ways:

\begin{equation}
\begin{aligned}
\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right) &= - \Psi\left({\bf r}_2,{\bf r}_1,\ldots, {\bf r}_N\right) \quad \text{fermions}, \\
\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right) &= + \Psi\left({\bf r}_2,{\bf r}_1,\ldots, {\bf r}_N\right) \quad \text{bosons}.
\end{aligned}
(\#eq:post6)  
\end{equation}

Each of the two options above characterize a different kind of particles. Those that have an antisymmetric wave function with respect to exchange of quantum states are called **fermions**, while those that have a symmetric one are called **bosons**. Eq. \@ref(eq:post6) is known in physics as *the spin-statistics theorem*. 

But why would the spin of a particle be important in the description of a multi-particle system? To understand this fact we can use the spin-statistics theorem to derive the much more popular^[at least in chemistry] *Pauli exclusion principle*. Let's start with a multi-fermionic wave function:

\begin{equation}
\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right) = - \Psi\left({\bf r}_2,{\bf r}_1,\ldots, {\bf r}_N\right),
(\#eq:postpauli2)  
\end{equation}

and then let's force two fermions (for simplicity of notation, let's take $1$ and $2$) into the same state, ${\bf r}_1={\bf r}_2$. So if we exchange the quantum states of these two fermions, nothing can change, because they are in the same state (we forced them to be in it), therefore we must also have:

\begin{equation}
\Psi\left({\bf r}_1,{\bf r}_2,\ldots, {\bf r}_N\right) = \Psi\left({\bf r}_2,{\bf r}_1,\ldots, {\bf r}_N\right).
(\#eq:postpauli3)  
\end{equation}

The only way both eqs. \@ref(eq:postpauli2) and \@ref(eq:postpauli3) can be fulfilled simultaneously is if $\Psi=0$. From this we can derive the Pauli exclusion principle, that says that if we have two fermions, they cannot share the same quantum state (the wave function for such case will need to be exactly zero everywhere). In summary, if we need to describe a system composed of many fermions, then we need to account for all of their individual spin. That is because if two fermions share the same position in space $\{x,y,z\}$, then their spin must be different. Or alternatively, if two fermions have the same spin, they will never occupy the same position in space. Notice that using a similar argument it's very easy to demonstrate that there is no Pauli exclusion principle for Bosons. Several bosons can all occupy the same position in space, regardless of their spin.^[See, for example, Bose-Einstein condensates [here.](https://en.wikipedia.org/wiki/Bose–Einstein_condensate)] Unfortunately (or perhaps fortunately), electrons are bosons...

## Chapter Review {#rev8}
### Study Questions {#quest8}

**1. According to postulate 1 in this chapter, what completely specifies the state of a quantum system?**

a. A set of classical coordinates and momenta  
b. A normalized wave function $\psi(\mathbf{r},t)$ over configuration space  
c. The list of all possible measurement outcomes  
d. The expectation values of all observables  
e. The energy and total angular momentum  

---

**2. In the wave function postulate, $|\psi(\mathbf{r},t)|^2 d\tau$ is interpreted as:**

a. The probability that the particle is found in volume element $d\tau$ around $\mathbf{r}$ at time $t$
b. The charge density of the particle  
c. The kinetic energy density  
d. The number of particles per unit volume  
e. The potential energy at $\mathbf{r}$


---

**3. Postulate 2 (experimental observables) states that to every classical observable there corresponds what?**

a. A real‑valued function of time only  
b. A complex number  
c. A linear Hermitian operator acting on wave functions  
d. A non‑linear operator that may not be hermitian  
e. A classical random variable  

---

**4. Why must operators representing physical observables be Hermitian?**

a. To guarantee that eigenvalues are integers  
b. To ensure that eigenfunctions are always real  
c. To guarantee real measurement outcomes (real eigenvalues)  
d. To make the Hamiltonian time independent  
e. To enforce energy conservation in all processes  

---

**5. If the system is in an eigenstate of $\hat{a}$ with eigenvalue $a_k$, what does postulate 3 say about the outcome of a measurement of $a$?**

a. The outcome is random among all eigenvalues  
b. The outcome is always $a_k$  
c. The outcome is always $\langle a\rangle$  
d. The outcome is one of two possible eigenvalues with equal probability  
e. The outcome is complex  

---

**6. In postulate 4, once a measurement yields a particular eigenvalue $a_k$, what happens to the wave function (in the idealized description)?**

a. It remains unchanged  
b. It collapses to the corresponding eigenstate of $\hat{a}$  
c. It becomes identically zero  
d. It becomes a uniform superposition of all eigenstates  
e. It collapses to the ground state of the hamiltonian  

---

**7. For a system in a superposition $\psi = \sum_k c_k \psi_k$ of $\hat{a}$-eigenfunctions $\psi_k$, what is the probability of obtaining eigenvalue $a_j$ upon measuring $a$?**

a. $|c_j|^2$ (assuming normalized eigenfunctions)  
b. $|a_j|^2$  
c. $1/|c_j|^2$  
d. Always $1/n$, where $n$ is the number of eigenvalues  
e. $\text{Re}(c_j)$  

---

**8. Postulate 5 implies that the time‑evolution operator must have which property?**

a. It is unitary, preserving normalization of $\psi$  
b. It is Hermitian  
c. It is real and symmetric  
d. It is diagonal in the position representation  
e. It always commutes with position  

---

**9. Postulate 6 in this chapter (Pauli exclusion principle) applies to which type of particles?**

a. All particles, regardless of spin  
b. Bosons only  
c. Fermions with half‑integer spin (e.g., electrons)  
d. Photons only  
e. Classical point particles

---

**10. What does the Pauli exclusion principle state about the many‑electron wave function for identical fermions?**

a. It must be symmetric under exchange of any two identical fermions  
b. It must vanish everywhere  
c. It must be antisymmetric under exchange of any two identical fermions  
d. It must be purely real  
e. It must be constant in space  

---

`r if (knitr::is_html_output()) {
  '
  Answers: <span style="cursor: pointer; color: blue; text-decoration: underline;" onclick="document.getElementById(\'reveal-inline-content\').style.display=\'inline\'; this.style.display=\'none\';">
    Click to reveal
  </span>
  <span id="reveal-inline-content" style="display: none;">
            1.b, 2.a, 3.c, 4.c, 5.b, 6.b, 7.a, 8.a, 9.c, 10.c
  </span>
  '
} else if (knitr::is_latex_output()) {
  'Answers: 1.b, 2.a, 3.c, 4.c, 5.b, 6.b, 7.a, 8.a, 9.c, 10.c'
}`

