# Introduction to Molecules {#Molecules}

## The Molecular Hamiltonian

For a molecule, we can decompose the Hamiltonian operator as:

\begin{equation}
\hat{H} = \hat{K}_N +\hat{K}_{e} + \hat{V}_{NN} + \hat{V}_{eN} + \hat{V}_{ee}
(\#eq:molham1)
\end{equation}

where we have decomposed the kinetic energy operator into nuclear and electronic terms, $\hat{K}_N$ and $\hat{K}_e$, as well as the potential energy operator into terms representing the interactions between nuclei, $\hat{V}_{NN}$, between electrons, $\hat{V}_{ee}$, and between electrons and nuclei, $\hat{V}_{eN}$. Each term can then be calculated using:

\begin{equation}
\begin{aligned}
\hat{K}_{N} &=-\sum_{i}^{\text{nuclei}}{\frac  {\hbar ^{2}}{2M_{i}}}\nabla_{{{\mathbf  {R}}_{i}}}^{2} \\
\hat  {K}_{e} &=-\sum_{i}^{\text{electrons}}{\frac  {\hbar ^{2}}{2m_{e}}}\nabla _{{{\mathbf{r}}_{i}}}^{2} \\
\hat{V}_{{NN}} &= \sum _{i}\sum _{{j>i}}{\frac  {Z_{i}Z_{j}e^{2}}{4\pi \varepsilon _{0}\left|{\mathbf  {R}}_{i}-{\mathbf  {R}}_{j}\right|}} \\
\hat  {V}_{{eN}} &=-\sum _{i}\sum _{j}{\frac  {Z_{i}e^{2}}{4\pi \varepsilon_{0}\left|{\mathbf  {R}}_{i}-{\mathbf  {r}}_{j}\right|}} \\
\hat{V}_{{ee}} &= \sum _{i}\sum _{{i<j}}{\frac  {e^{2}}{4\pi \varepsilon _{0}\left|{\mathbf  {r}}_{i}-{\mathbf  {r}}_{j}\right|}},
\end{aligned}
(\#eq:molham2)
\end{equation}

where $M_i$, $Z_i$, and $\mathbf{R}_i$ are the mass, atomic number, and coordinates of nucleus $i$, respectively, and all other symbols are the same as those used in eq. \@ref(eq:atom1) for the many-electron atom Hamiltonian.

### Small terms in the molecular Hamiltonian
The operator in eq. \@ref(eq:molham1) is known as the "exact" nonrelativistic Hamiltonian in field-free space. However, it is important to remember that it neglects at least two effects. Firstly, although the speed of an electron in a hydrogen atom is less than 1% of the speed of light, relativistic mass corrections can become appreciable for the inner electrons of heavier atoms. Secondly, we have neglected the spin-orbit effects, which is explained as follows. From the point of view of an electron, it is being orbited by a nucleus which produces a magnetic field (proportional to ${\bf L}$); this field interacts with the electron's magnetic moment (proportional to ${\bf S}$), giving rise to a spin-orbit interaction (proportional to  ${\bf L} \cdot {\bf S}$ for a diatomic.) Although spin-orbit effects can be important, they are generally neglected in quantum chemical calculations, and we will neglect them in the remainder of this textbook as well.

## The Born-Oppenheimer Approximation

As we already saw in the previous chapter, if a Hamiltonian is separable into two or more terms, then the total eigenfunctions are products of the individual eigenfunctions of the separated Hamiltonian terms. The total eigenvalues are then sums of individual eigenvalues of the separated Hamiltonian terms.

For example. let's consider a Hamiltonian that is separable into two terms, one involving coordinate $q_1$ and the other involving coordinate $q_2$:

\begin{equation}
\hat{H} = \hat{H}_1(q_1) + \hat{H}_2(q_2)
(\#eq:molham3)
\end{equation}

with the overall Schrödinger equation being:

\begin{equation}
\hat{H} \psi(q_1, q_2) = E \psi(q_1, q_2).
(\#eq:molham4)
\end{equation}

If we assume that the total wave function can be written in the form:

\begin{equation}
\psi(q_1, q_2) = \psi_1(q_1) \psi_2(q_2),
(\#eq:molham5)
\end{equation}

where $\psi_1(q_1)$ and $\psi_2(q_2)$ are eigenfunctions of $\hat{H}_1$ and $\hat{H}_2$ with eigenvalues $E_1$ and $E_2$, then:

\begin{equation}
\begin{aligned}
\displaystyle \hat{H} \psi(q_1, q_2) &= ( \hat{H}_1 + \hat{H}_2 ) \psi_1(q_1) \psi_2(q_2) \\
 	&= \hat{H}_1 \psi_1(q_1) \psi_2(q_2) + \hat{H}_2 \psi_1(q_1) \psi_2(q_2) \\
 	&= E_1 \psi_1(q_1) \psi_2(q_2) + E_2 \psi_1(q_1) \psi_2(q_2) \\
 	&= (E_1 + E_2) \psi_1(q_1) \psi_2(q_2) \\
 	&= E \psi(q_1, q_2)
\end{aligned}
(\#eq:molham6)
\end{equation}

Thus the eigenfunctions of $\hat{H}$ are products of the eigenfunctions of $\hat{H}_1$ and $\hat{H}_2$, and the eigenvalues are the sums of eigenvalues of $\hat{H}_1$ and $\hat{H}_2$.

If we examine the nonrelativistic Hamiltonian in eq. \@ref(eq:molham1), we see that the $\hat{V}_{eN}$ terms prevents us from cleanly separating the electronic and nuclear coordinates and writing the total wave function. If we neglect these terms, we can write the total wave function as:

\begin{equation}
\psi({\bf r}, {\bf R}) = \psi_e({\bf r}) \psi_N({\bf R}),
(\#eq:molham7)
\end{equation}

This approximation is called the **Born-Oppenheimer approximation**, and allows us to treat the nuclei as nearly fixed with respect to electron motion. The Born-Oppenheimer approximation is almost always quantitatively correct, since the nuclei are much heavier than the electrons and the (fast) motion of the latter does not affect the (slow) motion of the former. Using this approximation, we can fix the nuclear configuration at some value, ${\bf R_a}$, and solve for the electronic portion of the wave function, which is dependent only parametrically on ${\bf R}$ (we write this wave function as $\psi_e \left({\bf r}; {\bf R_a} \right)$, where the semicolon indicate the parametric dependence on the nuclear configuration).  To solve the TISEq we can then write the electronic Hamiltonian as:

\begin{equation}
\hat{H}_{\text{e}} = \hat{K}_e({\bf r}) +
\hat{V}_{eN}\left({\bf r}; {\bf R_a} \right) +
\hat{V}_{ee}({\bf r})
(\#eq:molham8)
\end{equation}

where we have also factored out the nuclear kinetic energy, $\hat{K}_N$ (since it is smaller than $\hat{K}_e$ by a factor of $\frac{M_i}{m_e}$), as well as $\hat{V}_{NN}({\bf R})$. This latter approximation is justified, since in the Born-Oppenheimer approximation ${\bf R}$ is just a parameter, and $\hat{V}_{NN}({\bf R_a})$ is a constant that shifts the eigenvalues only by some fixed amount. This electronic Hamiltonian results in the following TISEq:

\begin{equation}
\hat{H}_{e} \psi_e \left({\bf r}; {\bf R_a} \right) = E_{e} \psi_e \left({\bf r}; {\bf R_a} \right),
(\#eq:molham9)
\end{equation}

which is the equation that is used to explain the chemical bond in the next section. Notice that eq. \@ref(eq:molham9) is not the total TISEq of the system, since the nuclear eigenfunction and its eigenvalues (which can be obtained solving the Schrödinger equation with the nuclear Hamiltonian) are neglected.
As a final note, in the remainder of this textbook we will confuse the term "total energy" with "total energy at fixed geometry", as is customary in many other quantum chemistry textbooks (i.e., we are neglecting the nuclear kinetic energy). This is just $E_{e}$ of eq. \@ref(eq:molham9), plus the constant shift,$\hat{V}_{NN}({\bf R_a})$, given by the nuclear-nuclear repulsion.

## Solving the Electronic Eigenvalue Problem

Once we have invoked the Born-Oppenheimer approximation, we can attempt to solve the electronic TISEq in eq. \@ref(eq:molham9). However, for molecules with more than one electron, we need to—once again—keep in mind the antisymmetry of the wave function. This obviously means that we need to write the electronic wave function as a Slater determinant (i.e., all molecules but $\mathrm{H}_2^+$ and a few related highly exotic ions). Once this is done, we can work on approximating the Hamiltonian, a task that is necessary because the presence of the  electron-electron repulsion term forbids its analytic treatment. Similarly to the many-electron atom case, the simplest approximation to solve the molecular electronic TISEq is to use the variational method and to neglect the electron-electron repulsion. As we noticed in the previous chapter, this approximation is called the Hartree-Fock method.

### The Hartree-Fock Method
The main difference when we apply the variational principle to a molecular Slater determinant is that we need to build orbitals (one-electron wave functions) that encompass the entire molecule. This can be done by assuming that the atomic contributions to the molecular orbitals will closely resemble the orbitals that we obtained for the hydrogen atom. The total molecular orbital can then be built by linearly combine these atomic contributions. This method is called  **linear combination of atomic orbitals (LCAO)**. A consequence of the LCAO method is that the atomic orbitals on two different atomic centers are not necessarily orthogonal, and eq. \@ref(eq:var4) cannot be simplified easily. If we replace each atomic orbital $\psi(\mathbf{r})$ with a linear combination of suitable basis functions $f_i(\mathbf{r})$:

\begin{equation}
\psi(\mathbf{r}) = \sum_i^m c_{i} f_i(\mathbf{r}),
(\#eq:molham10)
\end{equation}

we can then use the following notation:

\begin{equation}
\displaystyle H_{ij} = \int \phi_i^* {\hat H} \phi_j d\mathbf{\tau}\;, \qquad \displaystyle S_{ij} = \int \phi_i^* \phi_jd\mathbf{\tau},
(\#eq:molham11)
\end{equation}

to simplify eq. \@ref(eq:var4) to:

\begin{equation}
E[\Phi] = \frac{\sum_{ij} c_i^* c_j H_{ij}}{\sum_{ij} c_i^* c_j S_{ij}}.
(\#eq:molham11b)
\end{equation}

Differentiating this energy with respect to the expansion coefficients $c_i$ yields a non-trivial solution only if the following "secular determinant" equals zero: 

\begin{equation}
\begin{vmatrix}
H_{11}-ES_{11}   & H_{12}-ES_{12}   & \cdots & H_{1m}-ES_{1m}\\
H_{21}-ES_{21}   & H_{22}-ES_{22}   & \cdots & H_{2m}-ES_{2m}\\
\vdots           &   \vdots         & \ddots & \vdots\\
H_{m1}-ES_{m1}   & H_{m2}-ES_{m2}   & \cdots & H_{mm}-ES_{mm}
\end{vmatrix}=0
(\#eq:molham12)
\end{equation}

where $m$ is the number of basis functions used to expand the atomic orbitals. Solving this set of equations with a Hamiltonian where the electron-electron correlation is neglected results is non-trivial, but possible. The reason for the complications comes from the fact that even if we are neglecting the direct interaction between electrons, each of them interact with the nuclei through an interaction that is screened by the average field of all other electrons, similarly to what we saw for the helium atom. This means that the Hamiltonian itself and the value of the coefficients $c_i$ in the wave function mutually depend on each other. A solution to this problem can be achieved numerically using specialized computer programs that use a cycle called the **self-consistent-field (SCF) procedure**. Starting from an initial guess of the coefficients, an approximated Hamiltonian operator is built from them and used to solve eq. \@ref(eq:molham12). This solution gives updated values of the coefficients, which can then be used to create an improved version of the approximated Hamiltonian. This procedure is repeated until both the coefficients and the operator do not change anymore. From this final solution, the energy of the molecule is then calculated.


## Chapter Review {#rev11}
### Study Questions {#quest11}

**1. In the full non‑relativistic molecular Hamiltonian (before approximations), which terms are present?**

a. only electronic kinetic energy and electron–nuclear attraction  
b. only nuclear kinetic energy and nuclear–nuclear repulsion  
c. spin–orbit and relativistic corrections only  
d. only electron–electron repulsion and nuclear–nuclear repulsion  
e. electronic and nuclear kinetic energies, electron–nuclear, electron–electron, and nuclear–nuclear interactions  

---

**2. What makes the exact molecular Schrödinger equation harder than the atomic case?**

a. electrons disappear in molecules  
b. nuclei can be treated classically in atoms but not in molecules  
c. the presence of multiple moving nuclei in addition to many electrons  
d. there is no coulomb interaction in molecules  
e. the electron mass changes in molecules  

---

**3. What is the central physical idea behind the Born–Oppenheimer approximation?**

a. electrons are much heavier than nuclei  
b. nuclei are much heavier than electrons, so electrons adjust almost instantaneously to nuclear motion  
c. electrons and nuclei move with the same characteristic time scale  
d. both electrons and nuclei can be treated as classical particles  
e. nuclei do not contribute to the energy at all  


---

**4. Mathematically, the Born–Oppenheimer approximation relies on what property of the Hamiltonian?**

a. exact commutation with the position operator  
b. separability into electronic and nuclear parts (plus interactions)  
c. absence of kinetic energy terms  
d. Hermiticity of the potential energy operator  
e. linearity of the time derivative  


---

**5. In practical quantum‑chemistry, what is usually meant (by abuse of language) by “total energy” of a molecule at fixed geometry?**

a. electronic energy $E_e$ at that geometry plus the constant nuclear–nuclear repulsion term  
b. nuclear kinetic energy only  
c. electronic energy without nuclear–nuclear repulsion  
d. purely classical potential energy  
e. nuclear vibrational zero‑point energy  

---

**6. Which of the following statements regarding potential‑energy surfaces (PESs) is correct?**

a. a PES is the graph of electronic energy as a function of nuclear geometry  
b. a PES is the graph of nuclear kinetic energy versus time  
c. a PES is independent of nuclear positions  
d. a PES depends only on electron spin  
e. PESs are defined only for diatomic molecules  


---

**7. Which of the following is *not* a direct consequence or assumption of the Born–Oppenheimer approximation?**

a. electronic and nuclear motions can be approximately separated  
b. electrons move in the field of fixed nuclei  
c. nuclear motion can be described on a pes obtained from electronic energies  
d. electron–nuclear coupling can never be important for any property  
e. total wavefunctions are approximated as products of electronic and nuclear parts  

---

**8. When the variational principle is applied to a Slater determinant built from molecular spin‑orbitals, minimizing the energy with respect to the orbital coefficients leads to what?**

a. the time‑dependent Schrödinger equation  
b. an over‑determined system with no nontrivial solutions  
c. a single algebraic equation for the total energy  
d. purely classical equations of motion for nuclei  
e. a set of coupled one‑electron equations involving the fock operator (Hartree–Fock equations)  

---

**9. Which of the following sentences describes the Fock operator $\hat{F}$ in Hartree–Fock theory?**

a. a two‑electron operator containing only electron–electron repulsion  
b. a purely nuclear operator  
c. a one‑electron effective operator containing kinetic, nuclear attraction, and averaged electron–electron (Coulomb and exchange) terms
d. an operator that depends only on spin and not on spatial coordinates  
e. the exact electronic Hamiltonian    

---

**10. In the Hartree–Fock method, how is the Pauli exclusion principle enforced for many‑electron systems?**

a. by forcing all electrons into different nuclei  
b. by requiring all spatial orbitals to be orthogonal but ignoring spin  
c. by constructing an antisymmetric Slater determinant of spin‑orbitals  
d. by adding a large repulsive potential at short inter‑electronic distances  
e. by using only hydrogen‑like orbitals  


---

`r if (knitr::is_html_output()) {
  '
  Answers: <span style="cursor: pointer; color: blue; text-decoration: underline;" onclick="document.getElementById(\'reveal-inline-content\').style.display=\'inline\'; this.style.display=\'none\';">
    Click to reveal
  </span>
  <span id="reveal-inline-content" style="display: none;">
            1.e, 2.c, 3.b, 4.b, 5.a, 6.a, 7.d, 8.e, 9.c, 10.c
  </span>
  '
} else if (knitr::is_latex_output()) {
  'Answers: 1.e, 2.c, 3.b, 4.b, 5.a, 6.a, 7.d, 8.e, 9.c, 10.c'
}`


